include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - 'build/**'
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - use_super_parameters
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_decorated_box
    - always_use_package_imports
